before_deploy: "echo 'ready?'"
language: node_js
node_js:
  - "6"
  - "8"
  - "9"
  - "10"
install:
  - npm install -g npm@latest
  - npm --version
  - npm install --registry http://registry.npmjs.org
script: npm run test:mocha
